// CountryDataService.swift
// countries.jsonを読み込んで国データを提供するサービス
// React NativeでいうAPIサービスやデータフェッチフックに相当

import Foundation
import CoreLocation

class CountryDataService {
    // シングルトンインスタンス
    static let shared = CountryDataService()

    private init() {}

    // countries.jsonから全国データを読み込む
    func loadCountries() -> [Country] {
        guard let url = Bundle.main.url(forResource: "countries", withExtension: "json") else {
            print("❌ countries.json が見つかりません")
            return []
        }

        do {
            let data = try Data(contentsOf: url)
            let decoded = try JSONDecoder().decode(CountriesData.self, from: data)
            return decoded.countries
        } catch {
            print("❌ JSON デコードエラー: \(error)")
            return []
        }
    }

    // 国コードで特定の国を検索する（例: "JP", "US"）
    func country(withCode code: String) -> Country? {
        loadCountries().first { $0.code == code }
    }

    // 国コードから地図上の座標を返す（195カ国対応）
    // 首都または国の中心付近の代表座標
    func coordinate(forCode code: String) -> CLLocationCoordinate2D {
        let coords: [String: CLLocationCoordinate2D] = [
            // アフリカ
            "DZ": CLLocationCoordinate2D(latitude: 28.0,   longitude:  3.0),
            "AO": CLLocationCoordinate2D(latitude: -11.2,  longitude: 17.9),
            "BJ": CLLocationCoordinate2D(latitude:  9.3,   longitude:  2.3),
            "BW": CLLocationCoordinate2D(latitude: -22.3,  longitude: 24.7),
            "BF": CLLocationCoordinate2D(latitude: 12.4,   longitude: -1.5),
            "BI": CLLocationCoordinate2D(latitude: -3.4,   longitude: 29.9),
            "CM": CLLocationCoordinate2D(latitude:  3.9,   longitude: 11.5),
            "CV": CLLocationCoordinate2D(latitude: 14.9,   longitude: -23.5),
            "CF": CLLocationCoordinate2D(latitude:  4.4,   longitude: 18.6),
            "TD": CLLocationCoordinate2D(latitude: 12.1,   longitude: 15.0),
            "KM": CLLocationCoordinate2D(latitude: -11.7,  longitude: 43.3),
            "CD": CLLocationCoordinate2D(latitude: -4.3,   longitude: 15.3),
            "CG": CLLocationCoordinate2D(latitude: -4.3,   longitude: 15.3),
            "CI": CLLocationCoordinate2D(latitude:  5.4,   longitude: -4.0),
            "DJ": CLLocationCoordinate2D(latitude: 11.8,   longitude: 42.6),
            "EG": CLLocationCoordinate2D(latitude: 26.8,   longitude: 30.8),
            "GQ": CLLocationCoordinate2D(latitude:  1.7,   longitude: 10.3),
            "ER": CLLocationCoordinate2D(latitude: 15.2,   longitude: 39.8),
            "ET": CLLocationCoordinate2D(latitude:  9.1,   longitude: 40.5),
            "GA": CLLocationCoordinate2D(latitude: -0.8,   longitude: 11.6),
            "GM": CLLocationCoordinate2D(latitude: 13.4,   longitude: -15.3),
            "GH": CLLocationCoordinate2D(latitude:  7.9,   longitude: -1.0),
            "GN": CLLocationCoordinate2D(latitude: 11.0,   longitude: -10.9),
            "GW": CLLocationCoordinate2D(latitude: 11.8,   longitude: -15.2),
            "KE": CLLocationCoordinate2D(latitude: -0.0,   longitude: 37.9),
            "LS": CLLocationCoordinate2D(latitude: -29.6,  longitude: 28.2),
            "LR": CLLocationCoordinate2D(latitude:  6.4,   longitude: -9.4),
            "LY": CLLocationCoordinate2D(latitude: 26.3,   longitude: 17.2),
            "MG": CLLocationCoordinate2D(latitude: -20.0,  longitude: 47.0),
            "MW": CLLocationCoordinate2D(latitude: -13.2,  longitude: 34.3),
            "ML": CLLocationCoordinate2D(latitude: 17.6,   longitude: -2.0),
            "MR": CLLocationCoordinate2D(latitude: 20.3,   longitude: -10.9),
            "MU": CLLocationCoordinate2D(latitude: -20.3,  longitude: 57.5),
            "MA": CLLocationCoordinate2D(latitude: 31.8,   longitude: -7.1),
            "MZ": CLLocationCoordinate2D(latitude: -18.7,  longitude: 35.5),
            "NA": CLLocationCoordinate2D(latitude: -22.0,  longitude: 17.1),
            "NE": CLLocationCoordinate2D(latitude: 17.6,   longitude:  8.1),
            "NG": CLLocationCoordinate2D(latitude:  9.1,   longitude:  8.7),
            "RW": CLLocationCoordinate2D(latitude: -2.0,   longitude: 30.0),
            "ST": CLLocationCoordinate2D(latitude:  0.2,   longitude:  6.6),
            "SN": CLLocationCoordinate2D(latitude: 14.5,   longitude: -14.5),
            "SC": CLLocationCoordinate2D(latitude: -4.7,   longitude: 55.5),
            "SL": CLLocationCoordinate2D(latitude:  8.5,   longitude: -11.8),
            "SO": CLLocationCoordinate2D(latitude:  5.2,   longitude: 46.2),
            "ZA": CLLocationCoordinate2D(latitude: -30.6,  longitude: 22.9),
            "SS": CLLocationCoordinate2D(latitude:  4.9,   longitude: 31.3),
            "SD": CLLocationCoordinate2D(latitude: 15.6,   longitude: 32.5),
            "SZ": CLLocationCoordinate2D(latitude: -26.5,  longitude: 31.5),
            "TZ": CLLocationCoordinate2D(latitude: -6.4,   longitude: 34.9),
            "TG": CLLocationCoordinate2D(latitude:  8.6,   longitude:  0.8),
            "TN": CLLocationCoordinate2D(latitude: 33.9,   longitude:  9.5),
            "UG": CLLocationCoordinate2D(latitude:  1.4,   longitude: 32.3),
            "ZM": CLLocationCoordinate2D(latitude: -13.1,  longitude: 27.8),
            "ZW": CLLocationCoordinate2D(latitude: -19.0,  longitude: 29.9),
            "EH": CLLocationCoordinate2D(latitude: 24.2,   longitude: -12.9),
            // アジア
            "AF": CLLocationCoordinate2D(latitude: 33.9,   longitude: 67.7),
            "AM": CLLocationCoordinate2D(latitude: 40.1,   longitude: 45.0),
            "AZ": CLLocationCoordinate2D(latitude: 40.1,   longitude: 47.6),
            "BH": CLLocationCoordinate2D(latitude: 26.0,   longitude: 50.6),
            "BD": CLLocationCoordinate2D(latitude: 23.7,   longitude: 90.4),
            "BT": CLLocationCoordinate2D(latitude: 27.5,   longitude: 90.4),
            "BN": CLLocationCoordinate2D(latitude:  4.5,   longitude: 114.7),
            "KH": CLLocationCoordinate2D(latitude: 12.6,   longitude: 104.9),
            "CN": CLLocationCoordinate2D(latitude: 35.9,   longitude: 104.2),
            "CY": CLLocationCoordinate2D(latitude: 35.1,   longitude: 33.4),
            "GE": CLLocationCoordinate2D(latitude: 42.3,   longitude: 43.4),
            "IN": CLLocationCoordinate2D(latitude: 20.6,   longitude: 79.1),
            "ID": CLLocationCoordinate2D(latitude: -0.8,   longitude: 113.9),
            "IR": CLLocationCoordinate2D(latitude: 32.4,   longitude: 53.7),
            "IQ": CLLocationCoordinate2D(latitude: 33.2,   longitude: 43.7),
            "IL": CLLocationCoordinate2D(latitude: 31.0,   longitude: 35.0),
            "JP": CLLocationCoordinate2D(latitude: 36.2,   longitude: 138.3),
            "JO": CLLocationCoordinate2D(latitude: 30.6,   longitude: 36.7),
            "KZ": CLLocationCoordinate2D(latitude: 48.0,   longitude: 66.9),
            "KW": CLLocationCoordinate2D(latitude: 29.3,   longitude: 47.5),
            "KG": CLLocationCoordinate2D(latitude: 41.2,   longitude: 74.8),
            "LA": CLLocationCoordinate2D(latitude: 17.9,   longitude: 102.5),
            "LB": CLLocationCoordinate2D(latitude: 33.9,   longitude: 35.5),
            "MY": CLLocationCoordinate2D(latitude:  4.2,   longitude: 108.0),
            "MV": CLLocationCoordinate2D(latitude:  3.2,   longitude: 73.2),
            "MN": CLLocationCoordinate2D(latitude: 46.9,   longitude: 103.8),
            "MM": CLLocationCoordinate2D(latitude: 17.1,   longitude: 96.9),
            "NP": CLLocationCoordinate2D(latitude: 28.4,   longitude: 84.1),
            "KP": CLLocationCoordinate2D(latitude: 40.3,   longitude: 127.5),
            "OM": CLLocationCoordinate2D(latitude: 21.5,   longitude: 55.9),
            "PK": CLLocationCoordinate2D(latitude: 30.4,   longitude: 69.3),
            "PS": CLLocationCoordinate2D(latitude: 31.9,   longitude: 35.2),
            "PH": CLLocationCoordinate2D(latitude: 12.9,   longitude: 121.8),
            "QA": CLLocationCoordinate2D(latitude: 25.4,   longitude: 51.2),
            "SA": CLLocationCoordinate2D(latitude: 23.9,   longitude: 45.1),
            "SG": CLLocationCoordinate2D(latitude:  1.4,   longitude: 103.8),
            "KR": CLLocationCoordinate2D(latitude: 35.9,   longitude: 127.8),
            "LK": CLLocationCoordinate2D(latitude:  7.9,   longitude: 80.8),
            "SY": CLLocationCoordinate2D(latitude: 34.8,   longitude: 38.9),
            "TW": CLLocationCoordinate2D(latitude: 23.7,   longitude: 121.0),
            "TJ": CLLocationCoordinate2D(latitude: 38.9,   longitude: 71.3),
            "TH": CLLocationCoordinate2D(latitude: 15.9,   longitude: 100.9),
            "TL": CLLocationCoordinate2D(latitude: -8.9,   longitude: 125.7),
            "TR": CLLocationCoordinate2D(latitude: 38.9,   longitude: 35.2),
            "TM": CLLocationCoordinate2D(latitude: 38.9,   longitude: 59.6),
            "AE": CLLocationCoordinate2D(latitude: 23.4,   longitude: 53.8),
            "UZ": CLLocationCoordinate2D(latitude: 41.4,   longitude: 64.6),
            "VN": CLLocationCoordinate2D(latitude: 14.1,   longitude: 108.3),
            "YE": CLLocationCoordinate2D(latitude: 15.6,   longitude: 48.5),
            "HK": CLLocationCoordinate2D(latitude: 22.3,   longitude: 114.2),
            "MO": CLLocationCoordinate2D(latitude: 22.2,   longitude: 113.5),
            // ヨーロッパ
            "AL": CLLocationCoordinate2D(latitude: 41.2,   longitude: 20.2),
            "AD": CLLocationCoordinate2D(latitude: 42.5,   longitude:  1.5),
            "AT": CLLocationCoordinate2D(latitude: 47.5,   longitude: 14.6),
            "BY": CLLocationCoordinate2D(latitude: 53.7,   longitude: 28.0),
            "BE": CLLocationCoordinate2D(latitude: 50.5,   longitude:  4.5),
            "BA": CLLocationCoordinate2D(latitude: 44.2,   longitude: 17.9),
            "BG": CLLocationCoordinate2D(latitude: 42.7,   longitude: 25.5),
            "HR": CLLocationCoordinate2D(latitude: 45.1,   longitude: 15.2),
            "CZ": CLLocationCoordinate2D(latitude: 49.8,   longitude: 15.5),
            "DK": CLLocationCoordinate2D(latitude: 56.3,   longitude:  9.5),
            "EE": CLLocationCoordinate2D(latitude: 58.6,   longitude: 25.0),
            "FI": CLLocationCoordinate2D(latitude: 61.9,   longitude: 25.7),
            "FR": CLLocationCoordinate2D(latitude: 46.2,   longitude:  2.2),
            "DE": CLLocationCoordinate2D(latitude: 51.2,   longitude: 10.5),
            "GR": CLLocationCoordinate2D(latitude: 39.1,   longitude: 22.0),
            "HU": CLLocationCoordinate2D(latitude: 47.2,   longitude: 19.5),
            "IS": CLLocationCoordinate2D(latitude: 65.0,   longitude: -18.6),
            "IE": CLLocationCoordinate2D(latitude: 53.1,   longitude: -8.2),
            "IT": CLLocationCoordinate2D(latitude: 41.9,   longitude: 12.6),
            "XK": CLLocationCoordinate2D(latitude: 42.6,   longitude: 20.9),
            "LV": CLLocationCoordinate2D(latitude: 56.9,   longitude: 24.6),
            "LI": CLLocationCoordinate2D(latitude: 47.1,   longitude:  9.6),
            "LT": CLLocationCoordinate2D(latitude: 55.2,   longitude: 24.0),
            "LU": CLLocationCoordinate2D(latitude: 49.8,   longitude:  6.1),
            "MT": CLLocationCoordinate2D(latitude: 35.9,   longitude: 14.4),
            "MD": CLLocationCoordinate2D(latitude: 47.4,   longitude: 28.4),
            "MC": CLLocationCoordinate2D(latitude: 43.7,   longitude:  7.4),
            "ME": CLLocationCoordinate2D(latitude: 42.7,   longitude: 19.4),
            "NL": CLLocationCoordinate2D(latitude: 52.1,   longitude:  5.3),
            "MK": CLLocationCoordinate2D(latitude: 41.6,   longitude: 21.7),
            "NO": CLLocationCoordinate2D(latitude: 60.5,   longitude:  8.5),
            "PL": CLLocationCoordinate2D(latitude: 51.9,   longitude: 19.1),
            "PT": CLLocationCoordinate2D(latitude: 39.4,   longitude: -8.2),
            "RO": CLLocationCoordinate2D(latitude: 45.9,   longitude: 24.9),
            "RU": CLLocationCoordinate2D(latitude: 61.5,   longitude: 105.3),
            "SM": CLLocationCoordinate2D(latitude: 43.9,   longitude: 12.5),
            "RS": CLLocationCoordinate2D(latitude: 44.0,   longitude: 21.0),
            "SK": CLLocationCoordinate2D(latitude: 48.7,   longitude: 19.7),
            "SI": CLLocationCoordinate2D(latitude: 46.2,   longitude: 14.8),
            "ES": CLLocationCoordinate2D(latitude: 40.5,   longitude: -3.7),
            "SE": CLLocationCoordinate2D(latitude: 60.1,   longitude: 18.6),
            "CH": CLLocationCoordinate2D(latitude: 46.8,   longitude:  8.2),
            "UA": CLLocationCoordinate2D(latitude: 48.4,   longitude: 31.2),
            "GB": CLLocationCoordinate2D(latitude: 55.4,   longitude: -3.4),
            "VA": CLLocationCoordinate2D(latitude: 41.9,   longitude: 12.5),
            // 北中南米
            "AG": CLLocationCoordinate2D(latitude: 17.1,   longitude: -61.8),
            "AR": CLLocationCoordinate2D(latitude: -38.4,  longitude: -63.6),
            "BS": CLLocationCoordinate2D(latitude: 25.0,   longitude: -77.4),
            "BB": CLLocationCoordinate2D(latitude: 13.2,   longitude: -59.5),
            "BZ": CLLocationCoordinate2D(latitude: 17.2,   longitude: -88.5),
            "BO": CLLocationCoordinate2D(latitude: -16.3,  longitude: -63.6),
            "BR": CLLocationCoordinate2D(latitude: -14.2,  longitude: -51.9),
            "CA": CLLocationCoordinate2D(latitude: 56.1,   longitude: -106.3),
            "CL": CLLocationCoordinate2D(latitude: -35.7,  longitude: -71.5),
            "CO": CLLocationCoordinate2D(latitude:  4.6,   longitude: -74.3),
            "CR": CLLocationCoordinate2D(latitude:  9.7,   longitude: -83.8),
            "CU": CLLocationCoordinate2D(latitude: 21.5,   longitude: -79.5),
            "DM": CLLocationCoordinate2D(latitude: 15.4,   longitude: -61.4),
            "DO": CLLocationCoordinate2D(latitude: 18.7,   longitude: -70.2),
            "EC": CLLocationCoordinate2D(latitude: -1.8,   longitude: -78.2),
            "SV": CLLocationCoordinate2D(latitude: 13.8,   longitude: -88.9),
            "GD": CLLocationCoordinate2D(latitude: 12.1,   longitude: -61.7),
            "GT": CLLocationCoordinate2D(latitude: 15.8,   longitude: -90.2),
            "GY": CLLocationCoordinate2D(latitude:  4.9,   longitude: -58.9),
            "HT": CLLocationCoordinate2D(latitude: 18.9,   longitude: -72.3),
            "HN": CLLocationCoordinate2D(latitude: 15.2,   longitude: -86.2),
            "JM": CLLocationCoordinate2D(latitude: 18.1,   longitude: -77.3),
            "MX": CLLocationCoordinate2D(latitude: 23.6,   longitude: -102.5),
            "NI": CLLocationCoordinate2D(latitude: 12.9,   longitude: -85.2),
            "PA": CLLocationCoordinate2D(latitude:  8.5,   longitude: -80.8),
            "PY": CLLocationCoordinate2D(latitude: -23.4,  longitude: -58.4),
            "PE": CLLocationCoordinate2D(latitude: -9.2,   longitude: -75.0),
            "KN": CLLocationCoordinate2D(latitude: 17.4,   longitude: -62.8),
            "LC": CLLocationCoordinate2D(latitude: 13.9,   longitude: -60.9),
            "VC": CLLocationCoordinate2D(latitude: 13.3,   longitude: -61.2),
            "SR": CLLocationCoordinate2D(latitude:  3.9,   longitude: -56.0),
            "TT": CLLocationCoordinate2D(latitude: 10.7,   longitude: -61.2),
            "US": CLLocationCoordinate2D(latitude: 37.1,   longitude: -95.7),
            "UY": CLLocationCoordinate2D(latitude: -32.5,  longitude: -55.8),
            "VE": CLLocationCoordinate2D(latitude:  6.4,   longitude: -66.6),
            // オセアニア
            "AU": CLLocationCoordinate2D(latitude: -25.3,  longitude: 133.8),
            "FJ": CLLocationCoordinate2D(latitude: -17.7,  longitude: 178.1),
            "KI": CLLocationCoordinate2D(latitude:  1.9,   longitude: -157.4),
            "MH": CLLocationCoordinate2D(latitude:  7.1,   longitude: 171.2),
            "FM": CLLocationCoordinate2D(latitude:  7.4,   longitude: 150.6),
            "NR": CLLocationCoordinate2D(latitude: -0.5,   longitude: 166.9),
            "NZ": CLLocationCoordinate2D(latitude: -40.9,  longitude: 174.9),
            "PW": CLLocationCoordinate2D(latitude:  7.5,   longitude: 134.6),
            "PG": CLLocationCoordinate2D(latitude: -6.3,   longitude: 143.9),
            "WS": CLLocationCoordinate2D(latitude: -13.8,  longitude: -172.1),
            "SB": CLLocationCoordinate2D(latitude: -9.6,   longitude: 160.2),
            "TO": CLLocationCoordinate2D(latitude: -21.2,  longitude: -175.2),
            "TV": CLLocationCoordinate2D(latitude: -7.1,   longitude: 177.6),
            "VU": CLLocationCoordinate2D(latitude: -15.4,  longitude: 166.9),
            // 領土・その他
            "GF": CLLocationCoordinate2D(latitude:  4.0,   longitude: -53.1),
            "GP": CLLocationCoordinate2D(latitude: 16.3,   longitude: -61.6),
            "MQ": CLLocationCoordinate2D(latitude: 14.6,   longitude: -61.0),
            "RE": CLLocationCoordinate2D(latitude: -21.1,  longitude: 55.5),
            "PM": CLLocationCoordinate2D(latitude: 46.9,   longitude: -56.3),
            "YT": CLLocationCoordinate2D(latitude: -12.8,  longitude: 45.2),
            "PF": CLLocationCoordinate2D(latitude: -17.7,  longitude: -149.4),
            "NC": CLLocationCoordinate2D(latitude: -21.0,  longitude: 165.6),
            "WF": CLLocationCoordinate2D(latitude: -13.8,  longitude: -177.2),
            "AQ": CLLocationCoordinate2D(latitude: -82.9,  longitude:  135.0),
            "GI": CLLocationCoordinate2D(latitude: 36.1,   longitude: -5.3),
            "FO": CLLocationCoordinate2D(latitude: 61.9,   longitude: -6.9),
            "GL": CLLocationCoordinate2D(latitude: 71.7,   longitude: -42.6),
            "BM": CLLocationCoordinate2D(latitude: 32.3,   longitude: -64.8),
            "KY": CLLocationCoordinate2D(latitude: 19.3,   longitude: -81.2),
            "TC": CLLocationCoordinate2D(latitude: 21.7,   longitude: -71.8),
            "VG": CLLocationCoordinate2D(latitude: 18.4,   longitude: -64.6),
            "VI": CLLocationCoordinate2D(latitude: 18.3,   longitude: -64.9),
            "PR": CLLocationCoordinate2D(latitude: 18.2,   longitude: -66.6),
            "GU": CLLocationCoordinate2D(latitude: 13.4,   longitude: 144.8),
            "MP": CLLocationCoordinate2D(latitude: 15.1,   longitude: 145.7),
            "AS": CLLocationCoordinate2D(latitude: -14.3,  longitude: -170.7),
            "CK": CLLocationCoordinate2D(latitude: -21.2,  longitude: -159.8),
            "NU": CLLocationCoordinate2D(latitude: -19.1,  longitude: -169.9),
            "TK": CLLocationCoordinate2D(latitude: -9.2,   longitude: -171.8),
            "NF": CLLocationCoordinate2D(latitude: -29.0,  longitude: 167.9),
            "CC": CLLocationCoordinate2D(latitude: -12.2,  longitude: 96.8),
            "CX": CLLocationCoordinate2D(latitude: -10.5,  longitude: 105.7),
            "AI": CLLocationCoordinate2D(latitude: 18.2,   longitude: -63.1),
            "FK": CLLocationCoordinate2D(latitude: -51.8,  longitude: -59.5),
            "SH": CLLocationCoordinate2D(latitude: -15.9,  longitude: -5.7),
            "IO": CLLocationCoordinate2D(latitude: -6.3,   longitude: 71.9),
            "MS": CLLocationCoordinate2D(latitude: 16.7,   longitude: -62.2),
            "PN": CLLocationCoordinate2D(latitude: -24.4,  longitude: -128.3),
            "GS": CLLocationCoordinate2D(latitude: -54.4,  longitude: -36.6),
            "SJ": CLLocationCoordinate2D(latitude: 77.6,   longitude: 23.7),
            "BV": CLLocationCoordinate2D(latitude: -54.4,  longitude:  3.4),
            "HM": CLLocationCoordinate2D(latitude: -53.1,  longitude: 73.5),
            "UM": CLLocationCoordinate2D(latitude: 19.3,   longitude: 166.6),
            "TF": CLLocationCoordinate2D(latitude: -49.3,  longitude: 69.3),
            "AW": CLLocationCoordinate2D(latitude: 12.5,   longitude: -70.0),
            "CW": CLLocationCoordinate2D(latitude: 12.2,   longitude: -69.0),
            "SX": CLLocationCoordinate2D(latitude: 18.0,   longitude: -63.1),
            "BQ": CLLocationCoordinate2D(latitude: 12.2,   longitude: -68.3),
            "BL": CLLocationCoordinate2D(latitude: 17.9,   longitude: -62.8),
            "MF": CLLocationCoordinate2D(latitude: 18.1,   longitude: -63.1),
            "IM": CLLocationCoordinate2D(latitude: 54.2,   longitude: -4.5),
            "JE": CLLocationCoordinate2D(latitude: 49.2,   longitude: -2.1),
            "GG": CLLocationCoordinate2D(latitude: 49.5,   longitude: -2.6),
            "AX": CLLocationCoordinate2D(latitude: 60.2,   longitude: 20.0),
        ]
        return coords[code] ?? CLLocationCoordinate2D(latitude: 0, longitude: 0)
    }
}
